// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "LASY AI na Prática — Do Zero à Renda com Apps de IA | Curso Completo",
  description: "Aprenda a criar aplicativos completos usando inteligência artificial, mesmo sem programar. Curso prático com 10 módulos + bônus exclusivo. Acesso imediato e garantia de 7 dias.",
  keywords: [
    "lasy ai",
    "curso inteligência artificial",
    "criar apps com ia",
    "aplicativos ia",
    "curso lasy",
    "monetizar apps",
    "apps sem programar",
    "inteligência artificial prática",
    "curso online ia",
    "desenvolvimento com ia"
  ],
  authors: [{ name: "LASY AI na Prática" }],
  creator: "LASY AI na Prática",
  publisher: "LASY AI na Prática",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
    },
  },
  openGraph: {
    type: "website",
    locale: "pt_BR",
    url: "https://seu-dominio.com",
    title: "LASY AI na Prática — Do Zero à Renda com Apps de IA",
    description: "Aprenda a criar aplicativos completos usando inteligência artificial, mesmo sem programar.",
    siteName: "LASY AI na Prática",
  },
  twitter: {
    card: "summary_large_image",
    title: "LASY AI na Prática — Do Zero à Renda com Apps de IA",
    description: "Aprenda a criar aplicativos completos usando inteligência artificial, mesmo sem programar.",
  },
  verification: {
    google: "seu-codigo-google-search-console",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
        <link rel="canonical" href="https://seu-dominio.com" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#0066FF" />
      </head>
      <body className={`${inter.variable} font-inter antialiased`}>
        {children}
      </body>
    </html>
  );
}
